name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  mobile-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Verificar formato
        run: dart format --set-exit-if-changed .

      - name: Analizar código
        run: flutter analyze

      - name: Correr tests
        run: flutter test